version: "2"
services:
  app:
    restart: 'always'
    image: php:7
    command: php -S 0.0.0.0:8000 -t /app/
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
      
  composer:
    restart: 'no'
    image: composer/composer:php7
    command: install --working-dir /app
    volumes:
      - ./src:/app

  pma:
   image: phpmyadmin/phpmyadmin
   ports:
    - "8181:80"
   environment:
     PMA_HOST: mariadb
     PMA_USER: root
     PMA_PASSWORD: password
     PHP_UPLOAD_MAX_FILESIZE: 1G
     PHP_MAX_INPUT_VARS: 1G
    

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: appUser
      MYSQL_PASSWORD: appPassword